{% set name = "BubbleDet" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/BubbleDet-{{ version }}.tar.gz
  sha256: 8245ae8e0ec593eb421a7034e2594c2a5712b501f02c4781abf2d08d6cab780e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - cosmotransitions >=2.0.6
    - findiff >=0.9.2
    - numpy >=1.21.5
    - packaging >=21.3
    - scipy >=1.8.0

test:
  imports:
    - BubbleDet
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://bubbledet.readthedocs.io/
  dev_url: https://bitbucket.org/og113/bubbledet/
  summary: 'A package for computing functional determinants'
  description: |
    BubbleDet is a Python package for computing functional determinants which
    arise in the bubble nucleation rate, whether in the context of early
    universe cosmology or table-top physics experiments.

extra:
  recipe-maintainers:
    - og113
    - AndreasEkstedt
    - joonashir
